### ISSUE TITLE
panos_panorama_tunnel_interface crashes

### ISSUE THREAD

**Issue by kbreit** [PaloAltoNetworks/terraform-provider-panos#326]
## Describe the bug

When running `panos_panorama_tunnel_interface` I am receiving a crash:

```
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs
│ may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with panos_panorama_tunnel_interface.gcp_tunnel,
│   on gcp_vpn.tf line 5, in resource "panos_panorama_tunnel_interface" "gcp_tunnel":
│    5: resource "panos_panorama_tunnel_interface" "gcp_tunnel" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs
│ may contain more details.
╵

Stack trace from the terraform-provider-panos_v1.10.0 plugin:

panic: interface conversion: interface {} is *pango.Panorama, not *pango.Firewall

goroutine 68 [running]:
github.com/terraform-providers/terraform-provider-panos/panos.readTunnelInterface(0xc000c1e690, 0x212e7a0, 0xc00000a1e0, 0xc000c1e690, 0x0)
	github.com/terraform-providers/terraform-provider-panos/panos/resource_tunnel_interface.go:104 +0x8f9
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0006870e0, 0xc00032d090, 0x212e7a0, 0xc00000a1e0, 0xc00000e4b8, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000cad38, 0x23711d0, 0xc000151410, 0xc000380ae0, 0xc0000cad38, 0xc000647ba0, 0x106ca87)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x20e9340, 0xc0000cad38, 0x23711d0, 0xc000151410, 0xc000380a80, 0x0, 0x23711d0, 0xc000151410, 0xc000906300, 0xb3)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a701c0, 0x237a8f8, 0xc000001980, 0xc000c42000, 0xc000726540, 0x2a99c10, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000a701c0, 0x237a8f8, 0xc000001980, 0xc000c42000, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005ec280, 0xc000a701c0, 0x237a8f8, 0xc000001980, 0xc000c42000)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-panos_v1.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## Expected behavior

It should create a tunnel interface in the proper Panorama template.

## Current behavior

See above for crash.

## Steps to reproduce

```
provider "panos" {
  hostname = "panorama-domain.example.com"
}

resource "panos_panorama_tunnel_interface" "gcp_tunnel" {
  template = "PAN-template"
  name = "tunnel.8"
  comment = "Tunnel for GCP demo"

  lifecycle {
      create_before_destroy = true
  }
}
```

## Your Environment

- Version used: 1.10.0
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): TF 1.1.5, Panorama 10.0.0
- Operating System and version (desktop or mobile): macOS
- Link to your project:

**Comment by jamesholland-uk** [comment]
Hi @kbreit, I can reproduce this error if I target a NGFW, but if I target Panorama it works fine. `panos_panorama_tunnel_interface` is designed for Panorama specifically. Are you targeting a NGFW or Panorama?

**Comment by kbreit** [comment]
@jamesholland-uk - I am definitely targeting Panorama. However, I wonder if the provider is caching some old values and internally pointing to a firewall. Looking into this a bit more. Do you happen to know how I can see the targets in state?

**Comment by kbreit** [comment]
@jamesholland-uk I don't have anything else `panos` related in the directory and right now the only thing I have enabled is the `panos` provider. However, if I enable this code snippet...
```
resource "panos_panorama_tunnel_interface" "gcp_tunnel" {
  template = "PAN-template"
  name = "tunnel.8"
  comment = "Tunnel for GCP, Transform 2022 demo"

  lifecycle {
      create_before_destroy = true
  }
}
```

I get...

```
Stack trace from the terraform-provider-panos_v1.10.0 plugin:

panic: interface conversion: interface {} is *pango.Panorama, not *pango.Firewall

goroutine 16 [running]:
github.com/terraform-providers/terraform-provider-panos/panos.readTunnelInterface(0xc000b24700, 0x212e7a0, 0xc00000a1e0, 0xc000b24700, 0x0)
```

As you said, it's inverted of what you're seeing. I am specifying the Panorama based resource but it's thinking it's panos. Regarding tstate, we're storing state in Azure so it's not local. But a `terraform state show panos_panorama_tunnel_interface.gcp_tunnel` isn't showing anything too exciting. It does include the `template` parameter.

**Comment by jamesholland-uk** [comment]
You could append this to your .tf file, to make sure it i definitely Panorama?!? No strange DNS resolving you to a NGFW?
```
data "panos_system_info" "device_info" { }

output "model" {
    value = data.panos_system_info.device_info.info.model
}
```

You should see something like:
```
Changes to Outputs:
  + model = "Panorama"
```
vs a NGFW model like this for VM-Series:
```
Changes to Outputs:
  + model = "PA-VM"
```

**Comment by kbreit** [comment]
I resolved this today. There were both panos and panos_panorama resources in state. So when it tried to scan the panos ones it got caught up with Panorama.

Is it feasible to catch this exception in code and provide a more friendly error?

**Comment by jamesholland-uk** [comment]
Glad it is sorted :-) The smoking gun was always `interface conversion: interface {} is *pango.Panorama, not *pango.Firewall`

If different error messages is an enhancement you would like to request, I'd ask that you open a separate GitHub Issue for it, and we can tag it as an enhancement and track it there. Many thanks
